\section{Introduction}

Condition-specific network activation is characteristic for cellular
systems and other real-world interaction networks. If measurements of
network states are available across a versatile set of conditions or
time points, it becomes possible to construct a global view of network
activation patterns. Different parts of the network respond to
different conditions, and in different ways. Systematic, data-driven
identification of these responses will help to obtain a holistic view
of network activity \cite{Lahti10bioinf, Lahti10thesis}. This package
provides robust probabilistic algorithms for functional network
analysis \cite{Lahti10bioinf, Parkkinen10bmcsysbio}. 

The methods are based on nonparametric probabilistic modeling and
variational learning, and provide general exploratory tools to
investigate the structure (ICMg; \cite{Parkkinen10bmcsysbio}) and
context-specific behavior (NetResponse; \cite{Lahti10bioinf}) of
interaction networks.  ICMg is used to identify community structure in
interaction networks; NetResponse detects and characterizes
subnetworks that exhibit context-specific activation patterns across
versatile collections of functional measurements, such as gene
expression data. The implementations are partially based on the
agglomerative independent variable group analysis \citep{Honkela08}
and variational Dirichlet process Gaussian mixture models
\cite{Kurihara07nips}. The tools are particularly useful for global
exploratory analysis of genome-wide interaction networks and versatile
collections of gene expression data.


\section{Loading the package and example data}

Each subnetwork response has a probabilistic association to each
condition. Get the list of samples corresponding to each response
(each sample is assigned to the response of the highest probability) with response2sample function.

<<resp, results = hide>>=
subnet.id <- 'Subnet-2'
response2sample(model, subnet.id)
@

Retrieve model parameters of a given subnetwork (Gaussian mixture
means, covariance diagonal, and component weights):
<<pars>>=
pars <- get.model.parameters(model, subnet.id) # model parameters
pars
@ 


Probabilistic sample-response assignments for a given subnet is retrieved with:
<<probs>>=
response.probabilities <- sample2response(model, subnet.id)
@

\section{Extending the subnetworks}

After identifying the locally connected subnetworks, it is possible to
search for features (genes) that are similar to a given subnetwork but
not directly interacting with it. To order the remaining features
in the input data based on similarity with the subnetwork, type

<<findsimilar>>=
g <- find.similar.features(model, subnet.id = "Subnet-1")
subset(g, delta < 0)
@

This gives a data frame which indicates similarity level with the
subnetwork for each feature. The smaller, the more similar. Negative
values of delta indicate the presence of coordinated responses,
positive values of delta indicate independent responses. The data
frame is ordered such that the features are listed by decreasing
similarity.

\section{Nonparametric Gaussian mixture models}

The package provides additional tools for nonparametric Gaussian
mixture modeling based on variational Dirichlet process mixture models
and implementations by \citep{Kurihara07nips, Honkela08}. See the
example in help(vdp.mixt).

\section{Interaction Component Model for Gene Modules}

Interaction Component Model (ICMg) can be used to find functional gene
modules \cite{Parkkinen10bmcsysbio} from either protein interaction
data or from combinations of protein interaction and gene expression
data.

A short example of how to run ICMg and obtain clustering for the nodes:

<<icmg, results = hide>>=
library(netresponse)
data(osmo)
res <- ICMg.combined.sampler(osmo$ppi, osmo$exp, C=10)
res$comp.memb <- ICMg.get.comp.memberships(osmo$ppi, res)
res$clustering <- apply(res$comp.memb, 2, which.max)
@


\begin{thebibliography}{1}

\bibitem{Lahti10bioinf}
Leo Lahti {\em et~al.} (2010).
\newblock Global modeling of transcriptional responses in interaction networks.
\newblock {\em Bioinformatics} 26(21):2713-20
\newblock Preprint available at: http://www.cis.hut.fi/lmlahti/publications/Lahti10bioinf-preprint.pdf

\bibitem{Lahti10thesis}
Leo Lahti (2010).                                     
\newblock Probabilistic analysis of the human transcriptome with side
information.                       
\newblock PhD thesis. TKK Dissertations in Information and Computer
Science TKK-ICS-D19. Aalto University School of Science and
Technology, Department of Information and Computer Science, Espoo,
Finland, December 2010
\newblock http://lib.tkk.fi/Diss/2010/isbn9789526033686/        
                    
\bibitem{Honkela08} Antti Honkela {\em et~al.} (2008). \newblock
Agglomerative independent variable group analysis. \newblock {\em
Neurocomputing\/} 71, 1311--20.

\bibitem{Kurihara07nips}
Kenichi Kurihara {\em et~al.} (2007).
\newblock Accelerated variational Dirichlet process mixtures.
\newblock In B.~Sch\"olkopf, J.~Platt, and T.~Hoffman, eds., {\em Advances
  in Neural Information Processing Systems 19\/}, 761-8. MIT Press,
  Cambridge, MA.

\bibitem{Parkkinen10bmcsysbio}
Parkkinen, J. and Kaski, S.
\newblock Searching for functional gene modules with interaction component models.
\newblock {\em BMC Systems Biology 4\/} (2010), 4.

\end{thebibliography}
